version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: "db"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
  django:
    build: ./api
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./api:/app/api
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    stdin_open: true
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - django

volumes:
  node-modules:
